module.exports = {
  content: ['./index.html', './src/**/*.{vue,js,ts,jsx,tsx}'],
  theme: {
    extend: {},
  },
  plugins: [
    require('@tailwindcss/typography'),
    require('daisyui'),
    require('@tailwindcss/container-queries'),
  ],
  daisyui: {
    logs: false,
    darkTheme: 'dark',
    themes: [
      'light',
      'dark',
      {
        light: {
          primary: '#7da89d',
          'primary-content': '#050a09',
          secondary: '#7862a1',
          'secondary-content': '#e2deed',
          accent: '#ee8039',
          'accent-content': '#140601',
          neutral: '#cbe0de',
          'neutral-content': '#0f1212',
          'base-100': '#f9f6f0',
          'base-200': '#fcfbf7',
          'base-300': '#ededed',
          'base-content': '#4e4e4e',
          info: '#2a6651',
          'info-content': '#d3dfda',
          success: '#659143',
          'success-content': '#030701',
          warning: '#f6b64b',
          'warning-content': '#150c02',
          error: '#a63121',
          'error-content': '#f1d6d1',
        },
        dark: {
          primary: '#bfb0d6',
          'primary-content': '#0d0b10',
          secondary: '#72a89d',
          'secondary-content': '#040a09',
          accent: '#f7d8ad',
          'accent-content': '#15110b',
          neutral: '#1E293B',
          'neutral-content': '#cdd0d5',
          'base-100': '#0F172A',
          'base-200': '#0b1223',
          'base-300': '#080e1c',
          'base-content': '#f9f6f0',
          info: '#352461',
          'info-content': '#d2d0df',
          success: '#9dc278',
          'success-content': '#090e05',
          warning: '#f6b64b',
          'warning-content': '#150c02',
          error: '#dd513c',
          'error-content': '#110201',
        },
      },
    ],
  },
};
